import { GithubOutlined } from "@ant-design/icons"

const workingList = [
  {
    key: 1,
    title: "Spring template Awesome SOHO",
    description:
      "Small Office Home Office 에 최적화된 Java Backend 템플릿입니다. 확장 가능한 사용자/메뉴/권한/공통 관련을 제공하는 것이 목표입니다.",
    url: "https://github.com/users/comnori/projects/2",
    icon: GithubOutlined,
    isPrivate: true,
    tags: [
      "Java",
      "Spring Boot",
      "Spring Framework",
      "Spring Data JPA",
      "Spring Data JDBC",
      "Spring Data Redis",
      "Spring Data REST",
      "Spring Security",
      "Spring Authorization Server",
      "Spring Rest Docs",
      "Spring Valut",
      "Hibernate",
      "Apche Kafka",
      "Redis",
      "Postgres",
      "devcontainer",
      "docker",
      "DDD (Domain Driven Degisn)",
      "CQRS",
      "EDD (Event Driven Design)",
      "TDD (Test Driven Develop)",
    ],
  },
  {
    key: 3,
    title: "Developer Resume and Blog",
    description:
      "Gatsby를 활용하여 개발자의 이력 및 블로그 포스팅을 위한 템플릿입니다. 현재 초급용 버전을 작업 중이며 중고급용 버전을 계획중에 있습니다. ",
    url: "https://github.com/users/comnori/comnori.github.com",
    icon: GithubOutlined,
    isPrivate: true,
    tags: ["gatsby", "graphql", "devcontainer", "github pages", "github actions"],
  },
  {
    key: 3,
    title: "DevOps template Awesome SOHO",
    description: "SOHO에서 사용하기 적합한 DevOps 패키지를 종합하여 개발환경 구축을 손쉽게 구축합니다.",
    url: "https://github.com/users/comnori/projects/6",
    icon: GithubOutlined,
    isPrivate: true,
    tags: [],
  },
  {
    key: 4,
    title: "RPA Project",
    description:
      "Spring template을 확장하여 BPM 기반의 RPA 시스템을 작성합니다. 사내의 주요 업무를 체계적으로 처리하는 것에 중점을 둡니다.",
    url: "https://github.com/users/comnori/projects/7",
    icon: GithubOutlined,
    tags: [],
  },
  {
    key: 5,
    title: "Private Crawler",
    description:
      "개인적인 관심사의 홈페이지/뉴스 피드/뉴스 레터 등의 정보를 crawling 하여 자동 번역 및 요약해서 한곳에서 확인할 수 있는 프로젝트입니다.",
    url: "https://github.com/users/comnori/projects/5",
    icon: GithubOutlined,
    isPrivate: true,
    tags: ["playwright", "Spring batch"],
  },
  {
    key: 6,
    title: "Homelab rebuild",
    description: "DevOps 템플릿을 사용하여 Home에서 전반적인 개발작업을 수행하는 것이 목표입니다.",
    url: "https://github.com/users/comnori/projects/9",
    icon: GithubOutlined,
    isPrivate: true,
    tags: [],
  },
]

const releaseList = [
  {
    key: 1,
    title: "cra-template-awesome-soho",
    description:
      "Docker기반 devcontainer에서 사전에 정의된 Node환경 / vscode 확장이 자동으로 이루어 집니다. 이로 인해 프로젝트를 바로 시작할 수 있습니다.",
    url: "https://github.com/comnori/cra-template-awesome-soho",
    icon: GithubOutlined,
    tags: [
      "Javascript",
      "Typescript",
      "React",
      "react-script",
      "redux",
      "ant design",
      "sass",
      "axios",
      "i18next",
      "eslint",
      "prettier",
      ".env",
      "editorconfig",
      "devcontainer",
      "sonarlint",
    ],
  },
  {
    key: 2,
    title: "vite-template-awesome-soho",
    description: "cra-template-awesome-soho를 vite로 변경한 프로젝트",
    url: "https://github.com/comnori/vite-template-awesome-soho",
    icon: GithubOutlined,
    tags: [
      "Javascript",
      "Typescript",
      "React",
      "react-script",
      "redux",
      "ant design",
      "sass",
      "axios",
      "i18next",
      "eslint",
      "prettier",
      ".env",
      "editorconfig",
      "devcontainer",
      "sonarlint",
      "yarn2",
      "vite",
      "vitest",
    ],
  },
  {
    key: 3,
    title: " vscode-javascript-pack ",
    description:
      "vscode 에서 JS/TS 작업 시 유용한 확장 모음 https://marketplace.visualstudio.com/items?itemName=comnori.js-awesome-soho-extension-pack",
    url: "https://github.com/comnori/vscode-javascript-pack",
    icon: GithubOutlined,
    tags: [],
  },
  {
    key: 4,
    title: " vscode-java-pack ",
    description:
      "vscode 에서 Java 작업 시 유용한 확장 모음 https://marketplace.visualstudio.com/items?itemName=comnori.java-spring-awesome-soho-extension-pack",
    url: "https://github.com/comnori/vscode-java-pack",
    icon: GithubOutlined,
    tags: [],
  },
]

export { releaseList, workingList }
